apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: myweb-rs1
spec:
   replicas: 3
   selector:
      matchLabels:
         env: production
   template:
      metadata:
          name: myweb-pod1
          labels:
             env: production
             region: IN
      spec:
         containers:
         - name: myweb-con1
           image: httpd  